#ifndef NETFIELDS_H
#define NETFIELDS_H

#include "defs.h"

DEMO_NAMESPACE_START

enum FieldType
{
    FIELD_FLOAT = 0,

    FIELD_INT_1 = 1,
    FIELD_INT_2 = 2,
    FIELD_INT_4 = 4,
    FIELD_INT_6 = 6,
    FIELD_INT_8 = 8,
    FIELD_INT_9 = 9,
    FIELD_INT_10 = 10, //stands for entity
    FIELD_INT_16 = 16,
    FIELD_INT_24 = 24,
    FIELD_INT_32 = 32,

    FIELD_INT_M8 = -8, //signed 8 bits
    FIELD_INT_M16 = -16, //signed 16 bits
};

struct Field
{
    const char* _name;
    FieldType	type;

};

/* 100% */
const Field EntityNetfield[] =
{
    {"pos.trTime",FIELD_INT_32},
    {"pos.trBase[1]",FIELD_FLOAT},
    {"pos.trBase[0]",FIELD_FLOAT},
    {"apos.trBase[1]",FIELD_FLOAT},
    {"pos.trBase[2]",FIELD_FLOAT},
    {"apos.trBase[0]",FIELD_FLOAT},
    {"pos.trDelta[0]",FIELD_FLOAT},
    {"pos.trDelta[1]",FIELD_FLOAT},
    {"eType",FIELD_INT_8},
    {"angles[1]",FIELD_FLOAT},
    {"pos.trDelta[2]",FIELD_FLOAT},
    {"origin[0]",FIELD_FLOAT},
    {"origin[1]",FIELD_FLOAT},
    {"origin[2]",FIELD_FLOAT},
    {"weapon",FIELD_INT_8},
    {"apos.trType",FIELD_INT_8},
    {"legsAnim",FIELD_INT_16},
    {"torsoAnim",FIELD_INT_16},
    {"genericenemyindex",FIELD_INT_32},
    {"eFlags",FIELD_INT_32},
    {"pos.trDuration",FIELD_INT_32},
    {"teamowner",FIELD_INT_8},
    {"groundEntityNum",FIELD_INT_10},
    {"pos.trType",FIELD_INT_8},
    {"angles[2]",FIELD_FLOAT},
    {"angles[0]",FIELD_FLOAT},
    {"solid",FIELD_INT_24},
    {"fireflag",FIELD_INT_2},
    {"event",FIELD_INT_10},
    {"customRGBA[3]",FIELD_INT_8},
    {"customRGBA[0]",FIELD_INT_8},
    {"speed",FIELD_FLOAT},
    {"clientNum",FIELD_INT_10},
    {"apos.trBase[2]",FIELD_FLOAT},
    {"apos.trTime",FIELD_INT_32},
    {"customRGBA[1]",FIELD_INT_8},
    {"customRGBA[2]",FIELD_INT_8},
    {"saberEntityNum",FIELD_INT_10},
    {"g2radius",FIELD_INT_8},
    {"otherEntityNum2",FIELD_INT_10},
    {"owner",FIELD_INT_10},
    {"modelindex2",FIELD_INT_8},
    {"eventParm",FIELD_INT_8},
    {"saberMove",FIELD_INT_8},
    {"apos.trDelta[1]",FIELD_FLOAT},
    {"boneAngles1[1]",FIELD_FLOAT},
    {"modelindex",FIELD_INT_M16},
    {"emplacedOwner",FIELD_INT_32},
    {"apos.trDelta[0]",FIELD_FLOAT},
    {"apos.trDelta[2]",FIELD_FLOAT},
    {"torsoFlip",FIELD_INT_1},
    {"angles2[1]",FIELD_FLOAT},
    {"lookTarget",FIELD_INT_10},
    {"origin2[2]",FIELD_FLOAT},
    {"modelGhoul2",FIELD_INT_8},
    {"loopSound",FIELD_INT_8},
    {"origin2[0]",FIELD_FLOAT},
    {"shouldtarget",FIELD_INT_1},
    {"trickedentindex",FIELD_INT_16},
    {"otherEntityNum",FIELD_INT_10},
    {"origin2[1]",FIELD_FLOAT},
    {"time2",FIELD_INT_32},
    {"legsFlip",FIELD_INT_1},
    {"bolt2",FIELD_INT_10},
    {"constantLight",FIELD_INT_32},
    {"time",FIELD_INT_32},
    {"hasLookTarget",FIELD_INT_1},
    {"boneAngles1[2]",FIELD_FLOAT},
    {"activeForcePass",FIELD_INT_6},
    {"health",FIELD_INT_10},
    {"loopIsSoundset",FIELD_INT_1},
    {"saberHolstered",FIELD_INT_2},
    {"npcSaber1",FIELD_INT_9},
    {"maxhealth",FIELD_INT_10},
    {"trickedentindex2",FIELD_INT_16},
    {"forcePowersActive",FIELD_INT_32},
    {"iModelScale",FIELD_INT_10},
    {"powerups",FIELD_INT_16},
    {"soundSetIndex",FIELD_INT_8},
    {"brokenLimbs",FIELD_INT_8},
    {"csSounds_Std",FIELD_INT_8},
    {"saberInFlight",FIELD_INT_1},
    {"angles2[0]",FIELD_FLOAT},
    {"frame",FIELD_INT_16},
    {"angles2[2]",FIELD_FLOAT},
    {"forceFrame",FIELD_INT_16},
    {"generic1",FIELD_INT_8},
    {"boneIndex1",FIELD_INT_6},
    {"NPC_class",FIELD_INT_8},
    {"apos.trDuration",FIELD_INT_32},
    {"boneOrient",FIELD_INT_9},
    {"bolt1",FIELD_INT_8},
    {"trickedentindex3",FIELD_INT_16},
    {"m_iVehicleNum",FIELD_INT_10},
    {"trickedentindex4",FIELD_INT_16},
    {"surfacesOff",FIELD_INT_32},
    {"eFlags2",FIELD_INT_10},
    {"isJediMaster",FIELD_INT_1},
    {"isPortalEnt",FIELD_INT_1},
    {"heldByClient",FIELD_INT_6},
    {"ragAttach",FIELD_INT_10},
    {"boltToPlayer",FIELD_INT_6},
    {"npcSaber2",FIELD_INT_9},
    {"csSounds_Combat",FIELD_INT_8},
    {"csSounds_Extra",FIELD_INT_8},
    {"csSounds_Jedi",FIELD_INT_8},
    {"surfacesOn",FIELD_INT_32},
    {"boneIndex2",FIELD_INT_6},
    {"boneIndex3",FIELD_INT_6},
    {"boneIndex4",FIELD_INT_6},
    {"boneAngles1[0]",FIELD_FLOAT},
    {"boneAngles2[0]",FIELD_FLOAT},
    {"boneAngles2[1]",FIELD_FLOAT},
    {"boneAngles2[2]",FIELD_FLOAT},
    {"boneAngles3[0]",FIELD_FLOAT},
    {"boneAngles3[1]",FIELD_FLOAT},
    {"boneAngles3[2]",FIELD_FLOAT},
    {"boneAngles4[0]",FIELD_FLOAT},
    {"boneAngles4[1]",FIELD_FLOAT},
    {"boneAngles4[2]",FIELD_FLOAT},
    {"userInt1",FIELD_INT_1},
    {"userInt2",FIELD_INT_1},
    {"userInt3",FIELD_INT_1},
    {"userFloat1",FIELD_INT_1},
    {"userFloat2",FIELD_INT_1},
    {"userFloat3",FIELD_INT_1},
    {"userVec1[0]",FIELD_INT_1},
    {"userVec1[1]",FIELD_INT_1},
    {"userVec1[2]",FIELD_INT_1},
    {"userVec2[0]",FIELD_INT_1},
    {"userVec2[1]",FIELD_INT_1},
    {"userVec2[2]",FIELD_INT_1},
};

/* 100% */
const Field PlayerNetfield[] =
{
    {"commandTime", FIELD_INT_32},
    {"origin[1]",FIELD_FLOAT},
    {"origin[0]",FIELD_FLOAT},
    {"viewangles[1]",FIELD_FLOAT},
    {"viewangles[0]",FIELD_FLOAT},
    {"origin[2]",FIELD_FLOAT},
    {"velocity[0]",FIELD_FLOAT},
    {"velocity[1]",FIELD_FLOAT},
    {"velocity[2]",FIELD_FLOAT},
    {"bobCycle", FIELD_INT_8},
    {"weaponTime", FIELD_INT_M16},
    {"delta_angles[1]", FIELD_INT_16},
    {"speed",FIELD_FLOAT},
    {"legsAnim", FIELD_INT_16},
    {"delta_angles[0]", FIELD_INT_16},
    {"torsoAnim", FIELD_INT_16},
    {"groundEntityNum", FIELD_INT_10},
    {"eFlags", FIELD_INT_32},
    {"fd.forcePower", FIELD_INT_8},
    {"eventSequence", FIELD_INT_16},
    {"torsoTimer", FIELD_INT_16},
    {"legsTimer", FIELD_INT_16},
    {"viewheight", FIELD_INT_M8},
    {"fd.saberAnimLevel", FIELD_INT_4},
    {"rocketLockIndex", FIELD_INT_10},
    {"fd.saberDrawAnimLevel", FIELD_INT_4},
    {"genericEnemyIndex", FIELD_INT_32},
    {"events[0]", FIELD_INT_10},
    {"events[1]", FIELD_INT_10},
    {"customRGBA[0]", FIELD_INT_8},
    {"movementDir", FIELD_INT_4},
    {"saberEntityNum", FIELD_INT_10},
    {"customRGBA[3]", FIELD_INT_8},
    {"weaponstate", FIELD_INT_4},
    {"saberMove", FIELD_INT_32},
    {"standheight", FIELD_INT_10},
    {"crouchheight", FIELD_INT_10},
    {"basespeed", FIELD_INT_M16},
    {"pm_flags", FIELD_INT_16},
    {"jetpackFuel", FIELD_INT_8},
    {"cloakFuel", FIELD_INT_8},
    {"pm_time", FIELD_INT_M16},
    {"customRGBA[1]", FIELD_INT_8},
    {"clientNum", FIELD_INT_10},
    {"duelIndex", FIELD_INT_10},
    {"customRGBA[2]", FIELD_INT_8},
    {"gravity", FIELD_INT_16},
    {"weapon", FIELD_INT_8},
    {"delta_angles[2]", FIELD_INT_16},
    {"saberCanThrow", FIELD_INT_1},
    {"viewangles[2]",FIELD_FLOAT},
    {"fd.forcePowersKnown", FIELD_INT_32},
    {"fd.forcePowerLevel[FP_LEVITATION]", FIELD_INT_2},
    {"fd.forcePowerDebounce[FP_LEVITATION]", FIELD_INT_32},
    {"fd.forcePowerSelected", FIELD_INT_8},
    {"torsoFlip", FIELD_INT_1},
    {"externalEvent", FIELD_INT_10},
    {"damageYaw", FIELD_INT_8},
    {"damageCount", FIELD_INT_8},
    {"inAirAnim", FIELD_INT_1},
    {"eventParms[1]", FIELD_INT_8},
    {"fd.forceSide", FIELD_INT_2},
    {"saberAttackChainCount", FIELD_INT_4},
    {"pm_type", FIELD_INT_8},
    {"externalEventParm", FIELD_INT_8},
    {"eventParms[0]", FIELD_INT_M16},
    {"lookTarget", FIELD_INT_10},
    {"weaponChargeSubtractTime", FIELD_INT_32},
    {"weaponChargeTime", FIELD_INT_32},
    {"legsFlip", FIELD_INT_1},
    {"damageEvent", FIELD_INT_8},
    {"rocketTargetTime", FIELD_INT_32}, //we have to manually convert pointer to (float*) pointer
    {"activeForcePass", FIELD_INT_6},
    {"electrifyTime", FIELD_INT_32},
    {"fd.forceJumpZStart",FIELD_FLOAT},
    {"loopSound", FIELD_INT_16},
    {"hasLookTarget", FIELD_INT_1},
    {"saberBlocked", FIELD_INT_8},
    {"damageType", FIELD_INT_2},
    {"rocketLockTime", FIELD_INT_32},
    {"forceHandExtend", FIELD_INT_8},
    {"saberHolstered", FIELD_INT_2},
    {"fd.forcePowersActive", FIELD_INT_32},
    {"damagePitch", FIELD_INT_8},
    {"m_iVehicleNum", FIELD_INT_10},
    {"generic1", FIELD_INT_8},
    {"jumppad_ent", FIELD_INT_10},
    {"hasDetPackPlanted", FIELD_INT_1},
    {"saberInFlight", FIELD_INT_1},
    {"forceDodgeAnim", FIELD_INT_16},
    {"zoomMode", FIELD_INT_2},
    {"hackingTime", FIELD_INT_32},
    {"zoomTime", FIELD_INT_32},
    {"brokenLimbs", FIELD_INT_8},
    {"zoomLocked", FIELD_INT_1},
    {"zoomFov",FIELD_FLOAT},
    {"fd.forceRageRecoveryTime", FIELD_INT_32},
    {"fallingToDeath", FIELD_INT_32},
    {"fd.forceMindtrickTargetIndex", FIELD_INT_16},
    {"fd.forceMindtrickTargetIndex2", FIELD_INT_16},
    {"lastHitLoc[2]",FIELD_FLOAT},
    {"fd.forceMindtrickTargetIndex3", FIELD_INT_16},
    {"lastHitLoc[0]",FIELD_FLOAT},
    {"eFlags2",FIELD_INT_10},
    {"fd.forceMindtrickTargetIndex4", FIELD_INT_16},
    {"lastHitLoc[1]",FIELD_FLOAT},
    {"fd.sentryDeployed", FIELD_INT_1},
    {"saberLockTime", FIELD_INT_32},
    {"saberLockFrame", FIELD_INT_16},
    {"fd.forcePowerLevel[FP_SEE]", FIELD_INT_2},
    {"saberLockEnemy", FIELD_INT_10},
    {"fd.forceGripCripple", FIELD_INT_1},
    {"emplacedIndex", FIELD_INT_10},
    {"holocronBits", FIELD_INT_32},
    {"isJediMaster", FIELD_INT_1},
    {"forceRestricted", FIELD_INT_1},
    {"trueJedi", FIELD_INT_1},
    {"trueNonJedi", FIELD_INT_1},
    {"duelTime", FIELD_INT_32},
    {"duelInProgress", FIELD_INT_1},
    {"saberLockAdvance", FIELD_INT_1},
    {"heldByClient", FIELD_INT_6},
    {"ragAttach", FIELD_INT_10},
    {"iModelScale", FIELD_INT_10},
    {"hackingBaseTime", FIELD_INT_16},
    {"userInt1", FIELD_INT_1},
    {"userInt2", FIELD_INT_1},
    {"userInt3", FIELD_INT_1},
    {"userFloat1", FIELD_INT_1},
    {"userFloat2", FIELD_INT_1},
    {"userFloat3", FIELD_INT_1},
    {"userVec1[0]", FIELD_INT_1},
    {"userVec1[1]", FIELD_INT_1},
    {"userVec1[2]", FIELD_INT_1},
    {"userVec2[0]", FIELD_INT_1},
    {"userVec2[1]", FIELD_INT_1},
    {"userVec2[2]", FIELD_INT_1},
};

/* 100% */
const Field PilotNetfield[] =
{
    {"commandTime", FIELD_INT_32},
    {"origin[1]",FIELD_FLOAT},
    {"origin[0]",FIELD_FLOAT},
    {"viewangles[1]",FIELD_FLOAT},
    {"viewangles[0]",FIELD_FLOAT},
    {"origin[2]",FIELD_FLOAT},
    {"weaponTime", FIELD_INT_M16},
    {"delta_angles[1]", FIELD_INT_16},
    {"delta_angles[0]", FIELD_INT_16},
    {"eFlags", FIELD_INT_32},
    {"eventSequence", FIELD_INT_16},
    {"rocketLockIndex", FIELD_INT_10},
    {"events[0]", FIELD_INT_10},
    {"events[1]", FIELD_INT_10},
    {"weaponstate", FIELD_INT_4},
    {"pm_flags", FIELD_INT_16},
    {"pm_time", FIELD_INT_M16},
    {"clientNum", FIELD_INT_10},
    {"weapon", FIELD_INT_8},
    {"delta_angles[2]", FIELD_INT_16},
    {"viewangles[2]",FIELD_FLOAT},
    {"externalEvent", FIELD_INT_10},
    {"eventParms[1]", FIELD_INT_8},
    {"pm_type", FIELD_INT_8},
    {"externalEventParm", FIELD_INT_8},
    {"eventParms[0]", FIELD_INT_M16},
    {"weaponChargeSubtractTime", FIELD_INT_32},
    {"weaponChargeTime", FIELD_INT_32},
    {"rocketTargetTime", FIELD_INT_32}, //we have to manually convert pointer to (float*) pointer
    {"fd.forceJumpZStart",FIELD_FLOAT},
    {"rocketLockTime", FIELD_INT_32},
    {"m_iVehicleNum", FIELD_INT_10},
    {"generic1", FIELD_INT_8},
    {"eFlags2",FIELD_INT_10},
    {"legsAnim", FIELD_INT_16},
    {"torsoAnim", FIELD_INT_16},
    {"torsoTimer", FIELD_INT_16},
    {"legsTimer", FIELD_INT_16},
    {"jetpackFuel", FIELD_INT_8},
    {"cloakFuel", FIELD_INT_8},
    {"saberCanThrow", FIELD_INT_1},
    {"fd.forcePowerDebounce[FP_LEVITATION]", FIELD_INT_32},
    {"torsoFlip", FIELD_INT_1},
    {"legsFlip", FIELD_INT_1},
    {"fd.forcePowersActive", FIELD_INT_32},
    {"hasDetPackPlanted", FIELD_INT_1},
    {"fd.forceRageRecoveryTime", FIELD_INT_32},
    {"saberInFlight", FIELD_INT_1},
    {"fd.forceMindtrickTargetIndex", FIELD_INT_16},
    {"fd.forceMindtrickTargetIndex2", FIELD_INT_16},
    {"fd.forceMindtrickTargetIndex3", FIELD_INT_16},
    {"fd.forceMindtrickTargetIndex4", FIELD_INT_16},
    {"fd.sentryDeployed", FIELD_INT_1},
    {"fd.forcePowerLevel[FP_SEE]", FIELD_INT_2},
    {"holocronBits", FIELD_INT_32},
    {"fd.forcePower", FIELD_INT_8},
    {"velocity[0]",FIELD_FLOAT},
    {"velocity[1]",FIELD_FLOAT},
    {"velocity[2]",FIELD_FLOAT},
    {"bobCycle", FIELD_INT_8},
    {"speed",FIELD_FLOAT},
    {"groundEntityNum", FIELD_INT_10},
    {"viewheight", FIELD_INT_M8},
    {"fd.saberAnimLevel", FIELD_INT_4},
    {"fd.saberDrawAnimLevel", FIELD_INT_4},
    {"genericEnemyIndex", FIELD_INT_32},
    {"customRGBA[0]", FIELD_INT_8},
    {"movementDir", FIELD_INT_4},
    {"saberEntityNum", FIELD_INT_10},
    {"customRGBA[3]", FIELD_INT_8},
    {"saberMove", FIELD_INT_32},
    {"standheight", FIELD_INT_10},
    {"crouchheight", FIELD_INT_10},
    {"basespeed", FIELD_INT_M16},
    {"customRGBA[1]", FIELD_INT_8},
    {"duelIndex", FIELD_INT_10},
    {"customRGBA[2]", FIELD_INT_8},
    {"gravity", FIELD_INT_16},
    {"fd.forcePowersKnown", FIELD_INT_32},
    {"fd.forcePowerLevel[FP_LEVITATION]", FIELD_INT_2},
    {"fd.forcePowerSelected", FIELD_INT_8},
    {"damageYaw", FIELD_INT_8},
    {"damageCount", FIELD_INT_8},
    {"inAirAnim", FIELD_INT_1},
    {"fd.forceSide", FIELD_INT_2},
    {"saberAttackChainCount", FIELD_INT_4},
    {"lookTarget", FIELD_INT_10},
    {"moveDir[1]",FIELD_FLOAT},
    {"moveDir[0]",FIELD_FLOAT},
    {"damageEvent", FIELD_INT_8},
    {"moveDir[2]",FIELD_FLOAT},
    {"activeForcePass", FIELD_INT_6},
    {"electrifyTime", FIELD_INT_32},
    {"damageType", FIELD_INT_2},
    {"loopSound", FIELD_INT_16},
    {"hasLookTarget", FIELD_INT_1},
    {"saberBlocked", FIELD_INT_8},
    {"forceHandExtend", FIELD_INT_8},
    {"saberHolstered", FIELD_INT_2},
    {"damagePitch", FIELD_INT_8},
    {"jumppad_ent", FIELD_INT_10},
    {"forceDodgeAnim", FIELD_INT_16},
    {"zoomMode", FIELD_INT_2},
    {"hackingTime", FIELD_INT_32},
    {"zoomTime", FIELD_INT_32},
    {"brokenLimbs", FIELD_INT_8},
    {"zoomLocked", FIELD_INT_1},
    {"zoomFov",FIELD_FLOAT},
    {"fallingToDeath", FIELD_INT_32},
    {"lastHitLoc[2]",FIELD_FLOAT},
    {"lastHitLoc[0]",FIELD_FLOAT},
    {"lastHitLoc[1]",FIELD_FLOAT},
    {"saberLockTime", FIELD_INT_32},
    {"saberLockFrame", FIELD_INT_16},
    {"saberLockEnemy", FIELD_INT_10},
    {"fd.forceGripCripple", FIELD_INT_1},
    {"emplacedIndex", FIELD_INT_10},
    {"isJediMaster", FIELD_INT_1},
    {"forceRestricted", FIELD_INT_1},
    {"trueJedi", FIELD_INT_1},
    {"trueNonJedi", FIELD_INT_1},
    {"duelTime", FIELD_INT_32},
    {"duelInProgress", FIELD_INT_1},
    {"saberLockAdvance", FIELD_INT_1},
    {"heldByClient", FIELD_INT_6},
    {"ragAttach", FIELD_INT_10},
    {"iModelScale", FIELD_INT_10},
    {"hackingBaseTime", FIELD_INT_16},
    {"userInt1", FIELD_INT_1},
    {"userInt2", FIELD_INT_1},
    {"userInt3", FIELD_INT_1},
    {"userFloat1", FIELD_INT_1},
    {"userFloat2", FIELD_INT_1},
    {"userFloat3", FIELD_INT_1},
    {"userVec1[0]", FIELD_INT_1},
    {"userVec1[1]", FIELD_INT_1},
    {"userVec1[2]", FIELD_INT_1},
    {"userVec2[0]", FIELD_INT_1},
    {"userVec2[1]", FIELD_INT_1},
    {"userVec2[2]", FIELD_INT_1},
};

/* 100% */
const Field VehicleNetfield[] =
{
    {"commandTime", FIELD_INT_32},
    {"origin[1]",FIELD_FLOAT},
    {"origin[0]",FIELD_FLOAT},
    {"viewangles[1]",FIELD_FLOAT},
    {"viewangles[0]",FIELD_FLOAT},
    {"origin[2]",FIELD_FLOAT},
    {"velocity[0]",FIELD_FLOAT},
    {"velocity[1]",FIELD_FLOAT},
    {"velocity[2]",FIELD_FLOAT},
    {"weaponTime", FIELD_INT_M16},
    {"delta_angles[1]", FIELD_INT_16},
    {"speed",FIELD_FLOAT},
    {"legsAnim", FIELD_INT_16},
    {"delta_angles[0]", FIELD_INT_16},
    {"groundEntityNum", FIELD_INT_10},
    {"eFlags", FIELD_INT_32},
    {"eventSequence", FIELD_INT_16},
    {"legsTimer", FIELD_INT_16},
    {"rocketLockIndex", FIELD_INT_10},
    {"events[0]", FIELD_INT_10},
    {"events[1]", FIELD_INT_10},
    {"weaponstate", FIELD_INT_4},
    {"pm_flags", FIELD_INT_16},
    {"pm_time", FIELD_INT_M16},
    {"clientNum", FIELD_INT_10},
    {"gravity", FIELD_INT_16},
    {"weapon", FIELD_INT_8},
    {"delta_angles[2]", FIELD_INT_16},
    {"viewangles[2]",FIELD_FLOAT},
    {"externalEvent", FIELD_INT_10},
    {"eventParms[1]", FIELD_INT_8},
    {"pm_type", FIELD_INT_8},
    {"externalEventParm", FIELD_INT_8},
    {"eventParms[0]", FIELD_INT_M16},
    {"vehOrientation[0]",FIELD_FLOAT},
    {"vehOrientation[1]",FIELD_FLOAT},
    {"moveDir[1]",FIELD_FLOAT},
    {"moveDir[0]",FIELD_FLOAT},
    {"vehOrientation[2]",FIELD_FLOAT},
    {"moveDir[2]",FIELD_FLOAT},
    {"rocketTargetTime", FIELD_INT_32},
    {"electrifyTime", FIELD_INT_32},
    {"loopSound", FIELD_INT_16},
    {"rocketLockTime", FIELD_INT_32},
    {"m_iVehicleNum", FIELD_INT_10},
    {"vehTurnaroundTime",FIELD_INT_32},
    {"hackingTime", FIELD_INT_32},
    {"brokenLimbs", FIELD_INT_8},
    {"vehWeaponsLinked",FIELD_INT_1},
    {"hyperSpaceTime",FIELD_INT_32},
    {"eFlags2",FIELD_INT_10},
    {"hyperSpaceAngles[1]",FIELD_FLOAT},
    {"vehBoarding",FIELD_INT_1},
    {"vehTurnaroundIndex",FIELD_INT_10},
    {"vehSurfaces",FIELD_INT_16},
    {"hyperSpaceAngles[0]",FIELD_FLOAT},
    {"hyperSpaceAngles[2]",FIELD_FLOAT},

    {"userInt1", FIELD_INT_1},
    {"userInt2", FIELD_INT_1},
    {"userInt3", FIELD_INT_1},
    {"userFloat1", FIELD_INT_1},
    {"userFloat2", FIELD_INT_1},
    {"userFloat3", FIELD_INT_1},
    {"userVec1[0]", FIELD_INT_1},
    {"userVec1[1]", FIELD_INT_1},
    {"userVec1[2]", FIELD_INT_1},
    {"userVec2[0]", FIELD_INT_1},
    {"userVec2[1]", FIELD_INT_1},
    {"userVec2[2]", FIELD_INT_1},
};

DEMO_NAMESPACE_END

#endif